spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: fR_80yuzadtwgkbZiH7y
            client-secret: VHjTU5VNwa
            redirect-uri: "http://localhost:8507/user/sns/naver/oauth2/code"
            authorization-grant-type: authorization_code
            scope: name, email
            client-name: Naver
          kakao:
            client-id: 12b4b3941b19e1352da8cc44e8be6ead
            redirect-uri: "http://localhost:8507/user/sns/kakao/oauth2/code"
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - openid
              - profile_nickname
              - account_email
              - gender
              - birthday
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
          kakao:
            authorization-uri: "https://kauth.kakao.com/oauth/authorize"
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id