server:
  port: 8507
  tomcat:
    uri-encoding: UTF-8

spring:
  main:
    banner-mode: off
  application:
    name: BankPin User Server
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  datasource:
    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost:3306/localdev?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: maria
    password: maria!

log4jdbc:
  spylogdelegator:
    name: net.sf.log4jdbc.log.slf4j.Slf4jSpyLogDelegator
  dump:
    sql:
      maxlinelength: 0
