server:
  port: 8507
  servlet:
    session: 10800
    context-path: /user
  tomcat:
    uri-encoding: UTF-8

log4jdbc:
  spylogdelegator:
    name: net.sf.log4jdbc.log.slf4j.Slf4jSpyLogDelegator
  dump:
    sql:
      maxlinelength: 0

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

mybatis:
  configuration:
    map-underscore-to-camel-case: true

spring:
  main:
    banner-mode: off
  application:
    name: BankPin User Server
  profiles:
    active: local
    group:
      "local": "local"
      "dev": "dev"
      "prod": "prod"

---
spring:
  config:
    activate:
      on-profile: local
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  datasource:
    url: jdbc:log4jdbc:mariadb://211.184.225.81:3306/abc?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ENC(CR4V6mQp8V32+wNNWZBwDA==)
    password: ENC(JTGUiqp/XIl8cUbQzl9bG9SnkQz/lxof)

---
server:
  port: 80
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: ENC(U+VESzvSUt1V4IBrWjh9Sv7o37ENBBPed8pbMawtTKYW1W0rnXml5PvIRDybnK1wrhCIDCePFeTW6l//fyF+hDGhJ2Qj6dmdG2+Sq0aWX6jwhmqXVKnjfMx/VSdr0EOZFOTiUO7v8kM=)
    username: ENC(CR4V6mQp8V32+wNNWZBwDA==)
    password: ENC(JTGUiqp/XIl8cUbQzl9bG9SnkQz/lxof)

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: ENC(U+VESzvSUt1V4IBrWjh9Sv7o37ENBBPed8pbMawtTKYW1W0rnXml5PvIRDybnK1wrhCIDCePFeTW6l//fyF+hDGhJ2Qj6dmdG2+Sq0aWX6jwhmqXVKnjfMx/VSdr0EOZFOTiUO7v8kM=)
    username: ENC(CR4V6mQp8V32+wNNWZBwDA==)
    password: ENC(JTGUiqp/XIl8cUbQzl9bG9SnkQz/lxof)
