spring:
  mail:
    naver:
      protocol: smtp
      host: smtp.naver.com
      port: 587
      username:
      password:
      properties:
        mail.smtp.auth: true
        mail.smtp.starttls.enable: true
        mail.smtp.ssl.trust: smtp.naver.com
        mail.smtp.ssl.protocols: TLSv1.2
    hiworks:
      host: smtps.hiworks.com
      port: 465
      username:
      password:
      properties:
        mail.smtp.auth: true
        mail.smtp.ssl.enable: true
        mail.smtp.ssl.protocols: TLSv1.2


environments:
  kcb:
    company-code: V59000000000