server:
  port: 8507
  servlet:
    context-path: /user
    session:
      timeout: 3600
  tomcat:
    uri-encoding: UTF-8

log4jdbc:
  spylogdelegator:
    name: net.sf.log4jdbc.log.slf4j.Slf4jSpyLogDelegator
  dump:
    sql:
      maxlinelength: 0

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  config: classpath:logback.xml

spring:
  main:
    banner-mode: off
  application:
    name: BankPin User Server
  config:
    import:
      - classpath:/application-oauth.yml
      - classpath:/application-import.yml
  profiles:
    active: local
    group:
      "local": "local"
      "dev": "dev"
      "prod": "prod"

---
spring:
  config:
    activate:
      on-profile: local
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  datasource:
    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://211.184.225.81:3306/bankpindb?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ENC(cDHA7G+0gyL4Km6tWaukWQ==)
    password: ENC(5DW5BtvDS4SrmOlNCsU5AKZTNhBmiqzl)

---
server:
  port: 80
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: ENC(322mDzu5E4Ul90Z2w3AY4QdSyd258Y2FBJGrseF7GBnL0FV8jN1V4v2y8ykfWBF0z5uL0BXaqU/oBiaVjmph1WeKdxU8SnwAxkDFjlBeiexFUmYt0Rbkv52C+lskcm0rGKjkpaHgmNWlMQ3ik7/uvA==)
    username: ENC(VFVMBkVSn2AtXkGMOpz8Xw==)
    password: ENC(J9CHAgPRGrDJARcO09ebfXVaEHpZRLso)

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: ENC(322mDzu5E4Ul90Z2w3AY4QdSyd258Y2FBJGrseF7GBnL0FV8jN1V4v2y8ykfWBF0z5uL0BXaqU/oBiaVjmph1WeKdxU8SnwAxkDFjlBeiexFUmYt0Rbkv52C+lskcm0rGKjkpaHgmNWlMQ3ik7/uvA==)
    username: ENC(VFVMBkVSn2AtXkGMOpz8Xw==)
    password: ENC(J9CHAgPRGrDJARcO09ebfXVaEHpZRLso)
